baseurl = "https://tz70s.github.io/"
title = "tz70s"
theme = "hugo-theme-slim"

[params]
  Subtitle = "Hacking distributed systems. Feel free to mail me or DM me at twitter if you need, I'll appreciate for any comments on my words."
  GithubID = "tz70s"
  TwitterID = "tz70s"
  DisqusShortname = "Tzu-Chiao Yeh"
  Summary = true
  Content = false
  FooterMsg = "me :: Tzu-Chiao Yeh @tz70s => su3g4284zo6y7@gmail.com"
