baseurl = "https://tz70s.github.io"
title = "tz70s"
theme = "vec"
languageCode = "zh-tw"
paginate = 10

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.main]]
    name = "about/me"
    weight = 1
    url = "/about"

[params]
  Keywords = ""
  Description = "Interested in Operating System recently"
  Avatar = "img/avatar.jpg"
  SelfIntro = "I don't need no TV screen..."
  Email = "su3g4284zo6y7@gmail.com"
  GithubID = "tz70s"
  TwitterID = "tz70s"
