baseurl = "https://tz70s.github.io"
DefaultContentLanguage = "en"
title = "I"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Learn Rust recently"
  logo = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  comments = true

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "tz70s"
  email = "su3g4284zo6y7@gmail.com"
  github = "tz70s"
  twitter = "tz70s"
  linkedin = "tz70s"
  instagram = "tzch1ao"
  soundcloud = "TzuChiaoYeh"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3

