baseurl = "https://tz70s.github.io/"
title = "tz70s"
theme = "hugo-theme-slim"

[params]
  Subtitle = "About distributed system, programming and system level stuff."
  GithubID = "tz70s"
  TwitterID = "tz70s"
  LinkedInID = "tzu-chiao-yeh-193697103"
  ResumeLink = "https://drive.google.com/open?id=1wm9KAGz5H3ljCvuG9IX0LK0poWGZvnPr"
  DisqusShortname = "Tzu-Chiao Yeh"
  Summary = true
  Content = false
  FooterMsg = "Tzu-Chiao Yeh { @tz70s, su3g4284zo6y7@gmail.com }"
  syntaxHighlighter = "highlight.js"
  mainSections = ["posts"]

[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4