baseurl = "https://tz70s.github.io/"
title = "tz70s"
theme = "hugo-theme-slim"

[params]
  Subtitle = "Distributed Systems, Databases and APIs."
  GithubID = "tz70s"
  TwitterID = "tz70s"
  LinkedInID = "tzu-chiao-yeh-193697103"
  ResumeLink = "https://drive.google.com/open?id=1wm9KAGz5H3ljCvuG9IX0LK0poWGZvnPr"
  DisqusShortname = "Tzu-Chiao Yeh"
  Summary = true
  Content = false
  FooterMsg = "Tzu-Chiao Yeh { @tz70s, su3g4284zo6y7@gmail.com }"
  syntaxHighlighter = "highlight.js"
  customCSS = ["https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/xcode.min.css"]
  mainSections = ["posts"]
